server:
  port: ${SERVER_PORT:8010}

spring:
  # Database Settings
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

    hikari:
      minimumIdle: ${DATASOURCE_MIN_IDLE:3}
      maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:5}
      maxLifeTime : ${DATASOURCE_MAX_LIFE_TIME:300000}


  # JPA Settings
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        show_sql: true
        connection:
          release_mode: auto
          autocommit: false
        generate_statistics: true
